version: 0.2

# env:
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"
#   exported-variables:
#     - variable
#     - variable
#   secrets-manager:
#     key: secret-id:json-key:version-stage:version-id
#   git-credential-helper: yes

# proxy:
#     upload-artifacts: yes
#     logs: yes

phases:
  install:
    commands:
      - npm i
    finally:
      - npm run lerna-install
  build:
    commands:
      - npm run build

  # test:
  #   commands:
  #     - npm run test
# reports:
#   report-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: yes
#     file-format: JunitXml | CucumberJson | VisualStudioTrx | TestNGXml
artifacts:
  files:
    - '**/*'
#   name: artifact-name
#   discard-paths: yes
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
cache:
  paths:
    - ./node_modules
    - ./client/node_modules
    - ./server/node_modules